; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3-ili9341-xpt2046]
board = esp32s3
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/esp32s3-ili9341-xpt2046>
board_build.arduino.memory_type = qio_qspi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

build_flags =
	${env.build_flags}
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1

	-D DEVICE_NAME='"ESP32-S3 ILI9341 XPT2046"'
	-D OTA_TAG='"esp32s3_ili9341_xpt2046"'

	-D ROTATION=0
	-D HAS_TOUCH=1
	-D HAS_RESISTIVE_TOUCH=1

	# LovyanGFX Driver Configuration
	-D USE_LOVYANGFX=1
	-D LOVYAN_PANEL=Panel_ILI9341
	-D LOVYAN_BUS=Bus_SPI

	# Display Pins and Settings
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_MEM_WIDTH=240
	-D TFT_MEM_HEIGHT=320
	-D TFT_OFFSET_X=0
	-D TFT_OFFSET_Y=0
	-D TFT_SCLK=12
	-D TFT_MOSI=11
	-D TFT_MISO=13
	-D TFT_DC=2
	-D TFT_CS=10
	-D TFT_RST=14
	-D TFT_BUSY=-1
	-D TFT_BL=21
	-D TFT_SPI_HOST=2
	-D TFT_SPI_MODE=0
	-D TFT_WRITE_FREQ=40000000
	-D TFT_READ_FREQ=16000000
	-D TFT_SPI_3WIRE=false
	-D TFT_USE_LOCK=true
	-D TFT_BUS_SHARED=false
	-D TFT_INVERTION=0
	-D TFT_RGB_ORDER=0

	# Touch Pins (XPT2046)
	-D CYD28_TouchR_CLK=6
	-D CYD28_TouchR_MOSI=5
	-D CYD28_TouchR_MISO=4
	-D CYD28_TouchR_CS=9
	-D CYD28_TouchR_IRQ=-1

lib_deps =
	${env.lib_deps}
	lovyan03/LovyanGFX@^1.2.0

lib_ignore =
	SensorLib
	XPowersLib
