; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs =
	esp32
    esp32s3
    esp32s2
    esp32c3
    esp32c5
    esp32c6
    esp32h2
    esp32p4

# Setup for common usage
build_cache_dir = ../../.pio/buildcache
cache_dir = ../../.pio/cache
core_dir = ../../.pio/core_maker
build_dir = ../../.pio/build

# Setup for codespaces
; build_dir = /tmp/.pio/build
; build_cache_dir = /tmp/.pio/buildcache
; cache_dir = /tmp/.pio/cache
; core_dir = /tmp/.pio/core

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
monitor_speed = 115200
framework = arduino
extra_scripts = post:copy_bins.py

[env:esp32]
board = esp32dev
board_build.partitions = partition.csv

[env:esp32c3]
board = esp32-c3-devkitc-02
board_build.partitions = partition.csv

[env:esp32c5]
board = esp32-c5-devkitc-1
board_build.partitions = partition.csv

[env:esp32c6]
board = esp32-c6-devkitc-1
board_build.partitions = partition.csv

[env:esp32h2]
board = esp32-h2-devkitm-1
board_build.partitions = partition.csv

[env:esp32p4]
board = esp32-p4
board_build.partitions = partition.csv

[env:esp32s2]
board = esp32-s2-kaluga-1
board_build.partitions = partition.csv

[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.partitions = partition.csv