; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-tab5]
board = esp32p4_es
#platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
#platform_packages = framework-arduinoespressif32-libs @ https://github.com/bmorcelli/esp32-arduino-lib-builder/releases/download/idf-release_v5.5/launcher_tab5_esp32-arduino-libs-20260519-233957.tar.xz
board_build.partitions = support_files/custom_16Mb_p4.csv
board_upload.speed = 1500000
build_src_filter =${env.build_src_filter} +<../boards/m5stack-tab5>
build_flags =
	${env.build_flags}
	-DM5STACK
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

	-DBOOT_LOGIC_ON_NVS=1

	-DDEVICE_NAME='"M5Stack Tab5"'
	-DOTA_TAG='"tab5"'

	-DUSE_M5GFX=1
	-DUSE_CARDKB2=1
	-DHAS_KEYBOARD=1
	-DCARDKB2_SDA=53
	-DCARDKB2_SCL=54

	-DROTATION=3

	-DHAS_TOUCH=1

	-DTFT_WIDTH=720
	-DTFT_HEIGHT=1280
	-DTFT_CS=5
	-DTFT_DC=14
	-DTFT_RST=12
	-DTOUCH_CS=-1
	-DTFT_MOSI=15
	-DTFT_SCLK=13
	-DTFT_BL=27

	-DTFT_IPS=0
	-DTFT_COL_OFS1=0
	-DTFT_ROW_OFS1=32
	-DTFT_COL_OFS2=0
	-DTFT_ROW_OFS2=0

	-D SDM=SD
	-D SDM_SD

	-DSDCARD_CS=42
	-DSDCARD_SCK=43
	-DSDCARD_MISO=39
	-DSDCARD_MOSI=44

	-D SDIO2_CLK=GPIO_NUM_12
	-D SDIO2_CMD=GPIO_NUM_13
	-D SDIO2_D0=GPIO_NUM_11
	-D SDIO2_D1=GPIO_NUM_10
	-D SDIO2_D2=GPIO_NUM_9
	-D SDIO2_D3=GPIO_NUM_8
	-D SDIO2_RST=GPIO_NUM_15

	-D BOARD_HAS_SDIO_ESP_HOSTED=1
	-D BOARD_SDIO_ESP_HOSTED_CLK=12
	-D BOARD_SDIO_ESP_HOSTED_CMD=13
	-D BOARD_SDIO_ESP_HOSTED_D0=11
	-D BOARD_SDIO_ESP_HOSTED_D1=10
	-D BOARD_SDIO_ESP_HOSTED_D2=9
	-D BOARD_SDIO_ESP_HOSTED_D3=8
	-D BOARD_SDIO_ESP_HOSTED_RESET=15

lib_deps =
	${env.lib_deps}
	m5stack/M5Unified @ ^0.2.17
	m5stack/M5Unit-KEYBOARD

lib_ignore =
	SensorLib
	XPowersLib
	GFX Library for Arduino

